import xmlrpc_redes as xmlrpc
import datetime
import sys

if len(sys.argv) >= 2:
    sv1_port = int(sys.argv[1])
else:
    sv1_port = 5000
if len(sys.argv) >= 3:
    sv2_port = int(sys.argv[2])
else:
    sv2_port = 5001
if len(sys.argv) >= 4:
    sv1_ip = str(sys.argv[3])
else:
    sv1_ip = '150.150.0.2'
if len(sys.argv) >= 5:
    sv2_ip = str(sys.argv[4])
else:
    sv2_ip = '100.100.0.2'

conn1 = xmlrpc.Client.connect(sv1_ip, int(sv1_port))
print(f'Estableciendo conexion con {sv1_ip}:{sv1_port}')

conn2 = xmlrpc.Client.connect(sv2_ip, int(sv2_port))
print(f'Estableciendo conexion con {sv2_ip}:{sv2_port}')
print()

print('Funciones Servidor1: ')

resultado1 = conn1.construirFloat(3, 14)
print(f'conn1.construirFloat(3, 14) = {resultado1}')
assert resultado1 == 3.14, f'Error en conn1.construirFloat: {resultado1} != 3.14'

resultado2 = conn1.divisionReales(10, 3.14)
print(f'conn1.divisionReales(10, 3.14) = {resultado2}')
assert resultado2 == 10/3.14, f'Error en conn1.divisionReales: {resultado2} != {10/3.14}'

resultado3 = conn1.fechaHora(24, 9, 2025, 8, 30, 0)
print(f'conn1.fechaHora(24, 9, 2025, 8, 30, 0) = {resultado3}')
assert resultado3 == datetime.datetime(2025, 9, 24, 8, 30, 0), f'Error en conn1.fechaHora: {resultado3} != {datetime.datetime(2025, 9, 24, 8, 30, 0)}'

resultado4 = conn1.xor(True, True)
print(f'conn1.xor(True, True) = {resultado4}')
assert resultado4 == False, f'Error en conn1.xor: {resultado4} != False'

resultado5 = conn1.dias(datetime.datetime(2024, 1, 1), datetime.datetime(2025, 1, 1))
print(f'conn1.dias(datetime.datetime(2024, 1, 1), datetime.datetime(2025, 1, 1)) = {resultado5}')
assert resultado5 == 366, f'Error en conn1.dias: {resultado5} != 366'

#<---------------- Casos que pidieron los profes -------------->

#Un request a un método sin parámetros y que retorna un único valor
resultado6 = conn1.holaMundo()
print(f'conn1.holaMundo() = {resultado6}')
assert resultado6 == "Hola Mundo!", f'Error en conn1.holaMundo: {resultado6} != "Hola Mundo!"'

#Un request a un método con parámetros entero y string y que retorna un único valor
resultado7 = conn1.concatStringEntero(5, "cinco -> ")
print(f'conn1.concatStringEntero(5, "cinco -> ") = {resultado7}')
assert resultado7 == "cinco -> 5", f'Error en conn1.concatStringEntero: {resultado7} != "cinco = 5"'

#Implementar un método que recibe un string y devuelve el mismo string (echo)
texto_largo = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula eros enim, sit amet tincidunt ante tincidunt id. Nullam at nisi arcu. Maecenas a orci maximus, pharetra ex at, suscipit lorem. Nam nec ligula luctus, pretium nunc ut, ultrices est. Praesent eleifend nisl eget ipsum varius, sed molestie neque condimentum. In placerat eros ac tristique auctor. Suspendisse pharetra mi ac ipsum sodales ultrices. Cras feugiat nunc eget pharetra fringilla. In sit amet augue mattis, consectetur velit vel, porta lorem. Vivamus vitae lacus ut mi dignissim consequat. Pellentesque et elit nec massa consequat fermentum in id neque.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque facilisis justo lacus, id condimentum mi convallis non. Cras congue commodo dui ac iaculis. Etiam et ligula dui. Phasellus congue augue vitae tristique bibendum. Sed convallis, odio ac elementum mattis, elit urna pretium ex, at tempor tortor arcu tincidunt sapien. Phasellus lobortis ipsum purus, nec elementum augue posuere in.

Sed at enim sit amet nulla pretium dignissim. Nunc sed nibh ultrices, elementum tortor id, iaculis arcu. Nullam imperdiet placerat tortor a tristique. Praesent vel lorem pretium, porta diam vitae, scelerisque ipsum. Pellentesque tellus magna, lobortis vel finibus id, sodales vitae est. Integer elit justo, sodales id sodales et, dignissim eu enim. Morbi non lectus justo. Fusce porta ligula a tristique pharetra. Phasellus convallis at urna sit amet vestibulum. Mauris blandit faucibus tristique. Nullam a nisi non nibh sagittis iaculis. Nullam venenatis odio ut sagittis sagittis. Fusce sem enim, eleifend vitae libero vitae, consequat varius ipsum.

Aliquam eleifend quam in purus ornare, condimentum facilisis ex molestie. Donec pulvinar bibendum ipsum, ac lobortis turpis dictum eu. Maecenas non turpis vel nulla elementum tristique. Sed tincidunt arcu turpis. Morbi eu felis vel turpis semper hendrerit et sed magna. Curabitur in tortor pharetra, lobortis leo ut, pellentesque lectus. Nunc imperdiet maximus nunc, in posuere tellus varius ut. Praesent vehicula nunc libero, ut venenatis elit feugiat at. Cras ut scelerisque lectus, id commodo diam. Curabitur eu est ac orci scelerisque mattis. Sed at consectetur erat. Curabitur vulputate, tortor non congue varius, enim nibh interdum neque, et lacinia augue nisi ac enim. Morbi mattis metus metus, ac tempus mauris mollis eu. Donec sed turpis maximus, ultricies odio et, placerat arcu. Nulla facilisi. Cras convallis leo in ex convallis, non rutrum felis lobortis.

Duis tincidunt ligula ut turpis aliquam, quis vehicula diam gravida. Nunc pellentesque leo pretium, molestie est ut, convallis ex. Aliquam vulputate mauris vitae pellentesque condimentum. Morbi sed eros sit amet mauris pulvinar sollicitudin ut eget justo. Phasellus nunc massa, tristique placerat dapibus a, ultricies id elit. Ut ullamcorper risus ac sem elementum bibendum. Duis vehicula euismod metus, ut euismod lectus ullamcorper et. Pellentesque interdum libero id mauris imperdiet, id aliquam lectus aliquet. Sed et lacinia odio. Cras id ultricies lectus.

Sed vel ultricies risus. Nam hendrerit ipsum placerat nulla venenatis, non lobortis mauris volutpat. Cras eget tincidunt ante. Nulla cursus eget nisi sollicitudin ultricies. In commodo sem sed magna sollicitudin accumsan. Curabitur pulvinar purus vel nunc elementum vulputate. Nullam vel enim eu nisl elementum pellentesque. Mauris sodales pharetra eleifend.

Nullam velit elit, feugiat vel turpis ut, iaculis venenatis lorem. Aenean at elementum lacus. Nunc dignissim turpis id dignissim maximus. Aliquam semper feugiat lorem ac placerat. Sed dapibus mauris ut nunc consectetur, in volutpat est volutpat. Etiam in est quis massa porta maximus eget ac nisl. Vestibulum pulvinar massa massa, quis ullamcorper quam pharetra nec.

Pellentesque nec metus arcu. Donec at lobortis ante, imperdiet accumsan tortor. Mauris interdum, mauris vitae molestie consequat, eros arcu aliquam ex, eu eleifend elit dolor non eros. Duis mattis urna et nulla lobortis, vel mattis nisl venenatis. Vivamus lacus eros, efficitur non sollicitudin efficitur, lacinia at justo. Pellentesque ut elementum massa. In eu metus dignissim dui efficitur tempor. Curabitur eu sapien quis purus varius maximus.

Proin luctus finibus facilisis. Duis tincidunt pretium urna sed molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam mattis, ex vel vehicula molestie, lectus ante mollis mauris, in fermentum erat arcu et ligula. Donec luctus suscipit quam ac facilisis. Donec eget volutpat massa, eu aliquet metus. Nunc eleifend sem non pulvinar vehicula. Vestibulum pellentesque ante quis magna vulputate, vel pretium lacus pulvinar.

Nulla varius sodales sem, quis lacinia mi sollicitudin nec. Etiam porta nunc a ante semper, id elementum nulla molestie. Cras sollicitudin, augue in congue laoreet, quam ante rhoncus nisl, in congue velit libero vel nulla. Donec blandit justo a maximus tincidunt. Sed et risus eget lectus porttitor facilisis at sed nulla. Sed dictum massa in justo condimentum, eget molestie nisi ultrices. Maecenas quis ligula nec diam volutpat commodo. In ornare lacus massa, ut molestie tellus feugiat at. Duis convallis nisi massa, ut dictum metus pharetra ac.

Sed semper eleifend massa et placerat. Donec id mauris vel nisl ullamcorper bibendum vel lacinia leo. Aenean fermentum sed eros quis aliquet. Donec euismod mollis risus sit amet scelerisque. Pellentesque sodales velit felis, at sagittis diam vulputate sit amet. In congue eleifend malesuada. Mauris in libero aliquam sapien sollicitudin euismod. Vivamus felis dolor, feugiat sed arcu eu, lacinia posuere purus.

Nullam consequat rhoncus mauris. Duis condimentum tortor in volutpat laoreet. Vivamus fermentum lacus sagittis dictum scelerisque. Quisque eget ex sed ipsum dapibus ultrices quis eget lorem. Nam a venenatis justo. Duis risus nunc, semper nec eros nec, iaculis gravida mi. Ut massa nibh, auctor sed ante et, maximus dapibus leo. Phasellus malesuada vestibulum sapien, sed faucibus dui tempor ut. Suspendisse congue, ex quis aliquam mattis, justo ligula auctor ligula, a euismod diam tortor ultricies mi. Ut quis augue nec magna condimentum tempor et sed ipsum.

Sed mattis libero quis lectus pretium, ornare iaculis neque congue. Sed lobortis porta libero eu auctor. In metus leo, laoreet vitae euismod a, imperdiet ut arcu. Curabitur cursus dignissim nisi. Curabitur ut vulputate velit, porttitor elementum nulla. Nunc tristique erat sed ullamcorper sagittis. Donec commodo fringilla quam, vel consectetur est sagittis congue. Vestibulum facilisis est at felis bibendum, ut elementum ex ultricies. Nullam in finibus sapien, sit amet lacinia nulla. Nullam at blandit dui. Nulla mollis feugiat libero, vel elementum ante. Sed risus ligula, rhoncus in volutpat sed, blandit nec lorem. Nullam iaculis est sit amet tincidunt posuere. Quisque auctor auctor elementum. Mauris venenatis ligula ac varius consequat.

Nunc facilisis non enim vitae facilisis. Quisque rhoncus lectus nunc, nec pellentesque ligula rhoncus non. Maecenas pretium enim quis enim maximus semper. Cras porttitor nunc et ante posuere, et maximus eros tincidunt. Aenean venenatis, libero vitae ultrices imperdiet, risus nulla rhoncus libero, eget facilisis tellus odio vitae ex. Nunc volutpat, elit at imperdiet vehicula, turpis odio tempus est, ac finibus orci purus vel quam. Suspendisse sagittis mollis placerat. Vestibulum nec volutpat est. Nulla facilisi. Phasellus faucibus risus vel nisi ornare facilisis. Ut ultricies dignissim est, nec imperdiet dui dictum in. Cras dignissim tortor metus, eu laoreet augue luctus a. Morbi non nulla vestibulum est tristique tempus.

Vivamus eu sollicitudin purus. In finibus leo nec nisi rutrum, ac mattis diam rhoncus. Ut ut elementum leo. Aenean ac cursus mauris. Nulla iaculis justo condimentum augue ullamcorper ornare. Donec porta efficitur libero nec volutpat. Fusce euismod gravida vulputate. Nam nec fermentum nisl. Fusce nec sem nibh.

Nam convallis turpis sit amet velit dictum, id pretium ante vulputate. Duis nisi sem, laoreet sed tellus vel, fringilla sollicitudin erat. Quisque ut suscipit massa. Quisque in diam id risus ultricies aliquet ut non ante. Suspendisse condimentum eros sem, id molestie justo egestas dignissim. Integer luctus imperdiet ex at imperdiet. Donec sit amet risus ac est vestibulum blandit. Duis porta orci non elit ornare, eu lobortis erat commodo. Vestibulum sed dui et odio porta ultricies. Aliquam vel velit dapibus, venenatis neque non, tristique mauris. Aliquam egestas lacus non justo semper condimentum.

Interdum et malesuada fames ac ante ipsum primis in faucibus. In bibendum ullamcorper elit eu volutpat. Nunc dapibus, dui eu dictum auctor, sem lorem imperdiet justo, a condimentum leo ipsum id erat. Aliquam gravida nulla in feugiat ultrices. Nullam aliquet volutpat magna in dapibus. Nam congue, ex id aliquam consectetur, lorem orci euismod enim, et placerat tortor lorem sed arcu. Curabitur ante lorem, finibus id arcu non, consequat consequat diam. Vestibulum tempus pretium gravida. Aliquam lobortis faucibus commodo. Quisque ornare nulla augue, sed mattis dui auctor bibendum. Donec molestie turpis eu nunc suscipit, vel consequat quam ornare. Curabitur consectetur nulla in tincidunt hendrerit.

Suspendisse commodo non eros in commodo. Donec bibendum ac felis ut ornare. Quisque velit metus, bibendum in lobortis eu, fringilla nec lorem. Maecenas eget tincidunt felis, nec tincidunt nunc. Nulla nulla massa, auctor nec felis id, rhoncus cursus nisl. Donec iaculis at urna ut gravida. Etiam in feugiat mauris, quis euismod nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras et ligula iaculis, accumsan mi et, faucibus mi. Aenean fringilla ut felis vel tempor. Phasellus nulla odio, pulvinar non dolor pulvinar, dictum pulvinar velit. Praesent volutpat nulla vel elit eleifend, a pulvinar leo vulputate. Nullam in felis vitae metus gravida ornare ut eu neque. Vestibulum facilisis, felis sed mattis faucibus, elit justo faucibus justo, eget volutpat turpis nulla id neque.

Nulla quam sapien, facilisis tempus nunc dignissim, laoreet fermentum eros. Nullam congue condimentum mattis. Mauris ac erat ut nisi sagittis ultrices. Integer ac lectus sed tellus convallis pretium. Quisque sit amet arcu vel neque facilisis consequat. Etiam pretium, erat et vestibulum dignissim, quam libero cursus risus, ac faucibus purus quam sed nisl. Curabitur felis dolor, dictum ut pretium et, cursus quis felis. Pellentesque maximus semper ex vel ullamcorper.

Nulla egestas in tortor at suscipit. Proin in tortor posuere, molestie erat eget, consequat nibh. Integer pulvinar suscipit finibus. In facilisis pulvinar vestibulum. In nisi metus, posuere in mi vitae, ullamcorper luctus erat. Aenean accumsan elementum magna eu volutpat. Suspendisse potenti. Cras quis cursus augue, quis suscipit neque. Curabitur pretium, enim ut varius fermentum, elit augue interdum nunc, id volutpat neque augue a erat. Aliquam vitae lorem quis nunc fermentum fringilla fermentum non velit. Nulla sed mi vel lacus posuere scelerisque et non nisi. Morbi arcu ligula, facilisis a dui et, lobortis mollis metus. Integer cursus libero vel ipsum malesuada volutpat.

Vivamus sed elit cursus, ultricies risus ut, rhoncus sapien. Etiam hendrerit euismod tortor, eget rutrum arcu vulputate et. Vestibulum convallis felis in risus cursus suscipit. Proin in nulla lacus. Etiam id elit ultricies, lobortis sem sed, cursus lorem. Nunc in nisl ullamcorper, imperdiet massa vel, maximus nibh. In hac habitasse platea dictumst. Maecenas at dolor nisl. Nunc est neque, imperdiet vel feugiat vitae, gravida a purus. Praesent facilisis, orci eu mollis hendrerit, odio lectus laoreet justo, vitae ullamcorper nunc tortor eu nisl. Maecenas interdum ipsum elit, a maximus nisi tempus at.

Suspendisse tempor libero at nunc aliquet, vel euismod nisl mattis. Donec id neque ultricies, accumsan ipsum quis, laoreet ex. Aenean eu malesuada felis. Donec eget nulla sollicitudin, convallis nisl at, dictum ex. Integer non lacus lorem. Aliquam erat volutpat. Mauris blandit dictum enim non elementum. Proin nisi sem, venenatis dignissim venenatis in, feugiat in turpis.

Nunc malesuada nulla id magna maximus, sit amet accumsan lectus porta. Mauris rhoncus orci dolor, vitae convallis turpis egestas in. Morbi laoreet ipsum in risus euismod, commodo porttitor justo placerat. Phasellus ullamcorper turpis et erat sodales auctor. Maecenas pharetra leo sed nibh molestie convallis. Duis et orci eu arcu accumsan viverra. Ut efficitur, odio vel fringilla semper, velit erat ultricies sem, a pretium felis justo quis ante. Pellentesque elementum leo massa, in tempus dolor sodales ut. In id arcu eget sem placerat vestibulum. Proin sit amet gravida sem. Nunc in dui sed nisi vehicula pretium eget a ligula. Maecenas non rhoncus neque, sit amet pharetra elit. Ut sit amet volutpat lectus, ac ultricies lorem. Maecenas ligula felis, iaculis sit amet luctus ac, finibus eget turpis.

Nulla feugiat dapibus ipsum, et accumsan leo aliquam egestas. Proin tempus tincidunt gravida. Etiam semper, dui non lacinia luctus, nulla enim consectetur felis, eu tristique mi risus a leo. Ut vulputate enim vel dolor interdum, auctor suscipit orci finibus. Etiam bibendum ornare tellus id fermentum. Nullam mollis magna augue, id cursus lectus commodo vel. Sed vitae ex vitae libero porttitor dapibus. Sed ullamcorper tincidunt metus, quis laoreet dui fermentum sit amet. Pellentesque rhoncus bibendum leo, at vestibulum odio. Donec semper posuere gravida. Vivamus vestibulum molestie tincidunt. Maecenas eleifend ut mauris porta cursus.

Duis porttitor eu orci auctor aliquam. Vivamus at ex et leo facilisis finibus. Etiam tristique posuere porta. Nam sit amet ultricies risus. Morbi a lacus vel justo aliquam vulputate. Vestibulum et efficitur velit, ut luctus nulla. Curabitur non sem placerat, vestibulum felis sed, rutrum urna. Cras et sapien vitae purus bibendum consectetur quis ut arcu.

Fusce eleifend lacinia orci, vitae interdum velit. In efficitur bibendum hendrerit. Pellentesque consectetur, lectus sit amet aliquam eleifend, tortor nulla sodales mauris, in molestie ante diam nec augue. Sed semper posuere iaculis. Duis eget cursus dui. Duis iaculis iaculis velit ac faucibus. Duis in elit vitae felis facilisis faucibus eget quis est. Fusce faucibus mi tellus, id ultricies lorem porttitor eu. Ut elementum sed nibh mattis rutrum. Suspendisse nec consequat elit, eu faucibus velit. Sed eget placerat ipsum. Duis non eros sed orci tincidunt egestas vitae eu arcu. Duis arcu leo, vestibulum porta luctus nec, varius convallis turpis. Fusce lectus metus, finibus id massa ac, ultricies elementum diam. Mauris cursus pretium purus, finibus molestie arcu vestibulum quis.

In ullamcorper vel nisi vitae eleifend. Donec ut iaculis sem. Vivamus tincidunt ipsum non tempus tincidunt. Proin pellentesque volutpat augue, sed maximus orci tincidunt nec. Praesent nec egestas mi, id viverra arcu. Aenean tellus nisl, malesuada sit amet odio eget, vulputate dapibus erat. Etiam id efficitur nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper varius vestibulum. Morbi id lorem vel arcu pellentesque tempus. Proin vitae enim condimentum tellus maximus pellentesque in sed sem.

In non magna ut turpis fringilla scelerisque in eu leo. Nam rutrum convallis iaculis. Vivamus tincidunt, ligula nec sollicitudin ultrices, odio diam molestie neque, eu vehicula dui arcu a lectus. Cras purus lorem, tempor eget arcu at, rhoncus congue nulla. Vivamus lorem dui, interdum quis mollis non, condimentum id urna. Vivamus hendrerit vehicula lectus, eu lobortis ligula congue eu. Sed nisl ante, feugiat vitae tincidunt ac, mattis in nulla. Fusce commodo, ligula ut imperdiet tincidunt, magna orci varius odio, at rutrum lectus elit in ipsum. Fusce nulla risus, iaculis eget tincidunt vel, euismod non metus.

Vestibulum turpis risus, tincidunt a velit id, sollicitudin hendrerit elit. Pellentesque porttitor nisi lorem, vel convallis libero dignissim eget. Etiam pretium lobortis tellus, vel tempor leo egestas sit amet. Fusce et mi condimentum, dapibus urna sed, consectetur enim. Proin interdum ultrices justo, non posuere leo lacinia sed. Fusce a sapien vel nisl convallis rutrum ut auctor nibh. In lorem risus, varius sit amet sodales ac, laoreet id arcu. Nulla quis elit justo.

Morbi et libero eget orci scelerisque malesuada ac congue metus. Mauris porttitor condimentum elit, sit amet lacinia ligula vehicula in. Phasellus in massa consectetur, pretium quam vitae, maximus massa. Pellentesque tempus ante at purus porta, eu cursus enim tincidunt. Nam dapibus eros id odio blandit rutrum. Donec condimentum vestibulum aliquet. Nulla facilisis libero leo, id rhoncus elit finibus nec. Nullam fringilla est ac cursus rhoncus. Aenean eu velit nunc. Aenean nec justo nec ante dignissim pellentesque vel vel mauris. Nam vel elementum justo.

Aliquam eu scelerisque lorem. Mauris tristique lacinia porta. Nunc porta, purus eget mattis convallis, ex elit ultricies odio, sit amet laoreet sapien libero auctor odio. Vivamus eu massa orci. Sed eu lobortis augue. Suspendisse vulputate, ipsum non efficitur pulvinar, enim justo interdum urna, vitae aliquam libero dui et odio. Nunc at ullamcorper nisi. Curabitur fringilla elit ut eleifend mollis. Proin sed tortor sagittis, pellentesque ex quis, dignissim ipsum. Duis rutrum quis neque non pretium. Vivamus ultricies lorem id facilisis vestibulum. Maecenas sodales magna neque, sit amet dignissim lacus rhoncus ut. Aliquam nec orci efficitur lacus mollis commodo vel eu orci.

Phasellus et risus sit amet sem pellentesque ultricies sed ut neque. Etiam sit amet nulla condimentum, eleifend mauris et, venenatis libero. Donec pulvinar nunc vel enim lacinia, convallis fermentum tortor lacinia. Proin lorem ex, ornare id auctor nec, sodales in tortor. Sed nec sapien a velit luctus finibus. Sed dapibus venenatis nunc vel commodo. Mauris ac fringilla quam. In elementum eros odio. Duis feugiat tincidunt accumsan. Sed mattis at mauris quis feugiat. Nam nec dolor in lacus aliquam molestie. Praesent dolor nulla, blandit vel volutpat finibus, viverra quis ligula. Ut eget dolor efficitur, sollicitudin dui at, maximus nisi.

Praesent eu urna et metus malesuada auctor. Fusce porttitor felis est, non mattis nulla semper vitae. Quisque et lectus ut mi blandit interdum non et velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur condimentum felis gravida, tincidunt purus ac, sollicitudin augue. Cras rhoncus mi turpis, id ornare odio ullamcorper in. In eget dignissim justo. Sed lacinia et odio quis mollis. Suspendisse nulla orci, placerat ut aliquam nec, pretium ut velit. Nunc felis lorem, ultricies non dictum quis, sodales eget elit. Suspendisse cursus diam quis nulla convallis egestas. Nulla tempor condimentum porta. Nunc et purus faucibus, aliquet ex in, sagittis massa.

Aenean id lorem non orci mollis fringilla. Curabitur vitae rhoncus orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam imperdiet ante ut enim interdum, et semper lorem rhoncus. Fusce volutpat odio ligula, ac mattis elit faucibus sed. Fusce consectetur magna vulputate ante rutrum aliquet ut at arcu. Phasellus ac felis orci. Nunc at augue vel leo blandit consectetur. Cras porta diam eleifend, malesuada mi quis, sagittis tortor. Integer convallis leo eu nunc porttitor, ac vulputate nisl commodo. Mauris aliquet leo ut libero dapibus dictum. Praesent suscipit arcu ut tellus ultrices, ut iaculis mauris sodales. Sed feugiat nisl id velit ultricies, quis eleifend nisi mollis. Etiam gravida gravida finibus. Aenean posuere non turpis in rutrum.

Ut efficitur mi et erat vulputate sodales. Pellentesque blandit, massa a gravida viverra, nisl urna pellentesque velit, nec egestas odio lectus id dui. Quisque fermentum tortor quis tristique cursus. Donec non volutpat dui. Curabitur et leo accumsan, accumsan orci ac, dapibus lectus. Quisque venenatis odio in velit commodo, quis consequat mauris ultricies. Pellentesque urna erat, malesuada non velit ac, molestie interdum diam. Integer fringilla, sapien vitae hendrerit semper, diam tortor facilisis mauris, quis volutpat diam lectus vel nisi. Nam sit amet lacus ipsum. Praesent vitae libero pellentesque, efficitur leo in, commodo urna. Vestibulum scelerisque dolor tempus sapien pretium, vitae commodo lectus ullamcorper. Quisque viverra elit dui, sed dignissim quam consectetur in. Aliquam quam nisi, faucibus nec velit iaculis, venenatis scelerisque velit. Sed molestie ligula non lacus venenatis, id volutpat mauris porta. Sed lobortis lectus odio, vel luctus massa aliquet vel.

Phasellus id massa in nulla pulvinar iaculis. Morbi non sapien id mi mattis porttitor vitae rhoncus sem. Nulla consectetur ullamcorper ipsum. Sed facilisis iaculis dolor, id bibendum diam congue nec. Morbi vel accumsan felis. Nullam sollicitudin est a blandit finibus. Nulla suscipit pulvinar nisi sit amet molestie. Nam et mattis ex, vel iaculis tortor. Proin ac quam sed urna varius rutrum. Sed malesuada erat eu accumsan scelerisque. Integer libero tellus, consequat ut orci in, aliquet pharetra eros. Ut diam ligula, semper fringilla semper eget, pharetra eget tellus. Donec egestas enim quam, vel tincidunt sapien semper eu. Vestibulum volutpat justo pretium tellus lacinia lobortis et in ligula. Quisque libero metus, posuere nec lacus sit amet, congue vehicula ante. Vestibulum feugiat, est at varius scelerisque, lacus ante pulvinar tellus, a tincidunt mi turpis ac quam.

Vivamus lectus ante, fringilla in enim eget, auctor molestie mi. Nulla elit neque, fermentum eget tempor a, gravida ut velit. Sed egestas neque a magna iaculis, consectetur mattis urna molestie. Cras id tortor at lacus mattis egestas aliquam tristique ligula. Aenean facilisis justo ultricies risus molestie, ut consequat sem pulvinar. Aenean lobortis semper ante eu pharetra. Nullam in fringilla nunc. Nulla a accumsan nulla. Vestibulum tincidunt eu ligula eget euismod. Phasellus sodales, neque ut euismod pulvinar, augue odio eleifend lectus, non vehicula orci mi at nisi. Quisque congue semper dolor a tristique. Fusce ex ante, placerat a sapien id, convallis lobortis metus. Vestibulum placerat scelerisque nulla eu mattis. Nunc cursus tortor sit amet enim tristique, sit amet suscipit est tristique.

Sed lacus libero, pulvinar eu elementum a, tempor ullamcorper nisi. Nulla ornare metus nunc, pretium dictum diam malesuada at. Cras eget pulvinar erat. Cras semper odio eget commodo iaculis. Integer ut nulla vel nibh consectetur volutpat. Nulla eu risus congue, sodales tortor vitae, imperdiet nisl. Nunc consectetur massa nec diam congue, vitae dapibus augue convallis. Sed dapibus eros a sem ultrices euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dui ut libero laoreet pharetra sit amet quis nisi.

Mauris maximus eros efficitur dolor dapibus cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. Nunc lorem nisl, sagittis nec cursus iaculis, cursus eget sem. Maecenas luctus sem turpis, vitae fermentum dui semper in. Sed porttitor vel tellus eu eleifend. Nunc vehicula ex mi, quis blandit mauris vehicula vel. Maecenas luctus magna in lectus porttitor, at convallis neque vehicula. Sed vel tempus lorem. Quisque sagittis mollis tellus quis lacinia. Phasellus vitae ultrices dui, et pharetra turpis. Nulla ligula risus, cursus nec suscipit ut, hendrerit nec eros. Aliquam eu ex odio. Maecenas nec augue bibendum lorem viverra sollicitudin.

Quisque ac mauris eleifend, faucibus purus non, placerat arcu. Sed nec nulla odio. Quisque eu ipsum nec dui finibus fringilla. Morbi lobortis ultricies felis vitae ornare. Suspendisse potenti. Sed tellus enim, placerat venenatis mauris eu, semper egestas lectus. Proin mattis nibh in magna finibus, quis gravida nibh rutrum.

Etiam vestibulum dictum accumsan. Ut vitae leo id dui tempor laoreet in et erat. Ut sit amet lacus sit amet sem convallis mattis. Nunc aliquam condimentum consectetur. Aenean varius facilisis turpis at lacinia. Proin fringilla, risus eu pharetra vehicula, massa lacus molestie nisi, a dapibus tortor nisl nec sapien. Curabitur bibendum tempus viverra. Cras posuere elit metus, id tincidunt turpis viverra sit amet. Aliquam tristique diam nisi, ut sodales velit porttitor vitae. Vestibulum sed nisl erat. Suspendisse condimentum sodales nunc, eget elementum purus dictum vel. Pellentesque ac consectetur tellus, vel finibus nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce felis tortor, volutpat eu tellus a, mollis aliquet nunc.

Aliquam sed libero bibendum, malesuada lectus vel, tincidunt dolor. Mauris maximus aliquet leo vel ultricies. Ut semper magna et nisl sagittis, sit amet efficitur massa vulputate. Cras magna massa, auctor ac tristique ultricies, pretium ut ipsum. Vestibulum mauris nunc, placerat ac porta ac, faucibus elementum nisl. Ut porta tellus turpis, eu fermentum risus pharetra vel. Vestibulum ligula sem, ullamcorper vitae mauris vel, malesuada consequat enim. Phasellus posuere mi eget tellus rutrum iaculis.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In auctor dignissim nisl ac cursus. Vestibulum efficitur bibendum lacus. Curabitur orci urna, ultricies vel egestas ac, tristique bibendum lectus. Phasellus aliquam lorem quis volutpat sollicitudin. Etiam consequat aliquam lorem non pretium. Quisque volutpat consectetur facilisis. Nulla dignissim dapibus ante, id suscipit lorem fermentum vitae. Quisque sit amet velit ut massa scelerisque dictum id a augue. Integer orci arcu, consectetur euismod condimentum vitae, euismod non nunc. Curabitur magna nulla, mollis quis sagittis ac, laoreet quis diam. Vestibulum varius, elit sit amet iaculis posuere, tellus erat faucibus tellus, vel sagittis lectus nulla eget nibh. Phasellus nec ante purus. Sed sollicitudin, nisl sit amet ullamcorper viverra, velit est ultricies metus, a hendrerit turpis augue quis dui. Maecenas et sem non est scelerisque sodales a faucibus turpis. In imperdiet ullamcorper ultrices.

Pellentesque cursus odio eget hendrerit pulvinar. Duis auctor ullamcorper leo, non maximus urna condimentum eget. Ut vehicula nunc a massa sodales mollis. Praesent et accumsan mauris. Sed eu ultrices neque, ut luctus sapien. Integer gravida fringilla cursus. Aenean id bibendum mi. Nulla vel tristique tortor, at eleifend ipsum. Fusce ornare urna eu lacus lobortis, sit amet rutrum lectus fermentum. Nullam non cursus arcu. Sed bibendum neque lacinia aliquam molestie. Sed volutpat nunc eu elit dapibus, quis fermentum felis ultricies. Pellentesque interdum hendrerit nisl ut maximus. Integer mauris diam, convallis et ipsum et, ultrices placerat quam. Donec feugiat felis vel ante fringilla mattis.

Nam eleifend neque libero, sit amet lobortis odio gravida varius. Pellentesque sollicitudin sem dolor, ac rhoncus magna accumsan eu. Suspendisse dictum eu ipsum et iaculis. Cras eget nisi ac nunc vestibulum tristique. Proin malesuada placerat justo quis convallis. Integer semper sapien ut dui consectetur, et lacinia tortor eleifend. Vivamus rutrum metus in enim elementum egestas. Mauris metus magna, mattis quis dapibus ut, rutrum nec sapien. Sed interdum vulputate risus sit amet mollis. Aliquam erat risus, tempus ac pharetra eu, tincidunt vitae lectus. Cras vestibulum ipsum sem, quis maximus enim fringilla ac. Pellentesque sit amet ipsum eu urna ultricies tincidunt ac ut felis. Aliquam mollis tellus justo, feugiat efficitur arcu volutpat non. Integer vel tortor dictum, tempor leo vitae, interdum ipsum. Nulla tincidunt, tortor ut facilisis posuere, nulla purus aliquet felis, non ultrices metus ante sit amet nulla. Morbi eu sagittis nulla.

Praesent tempor lacus in sem blandit, eu hendrerit orci pellentesque. Maecenas dapibus nunc sapien, vel commodo massa iaculis suscipit. Donec sodales augue est, ut accumsan lectus placerat et. Aenean lacinia vitae sapien et auctor. Nullam imperdiet magna ipsum. Nam lobortis ultrices massa sed accumsan. Ut in massa tincidunt, aliquam dolor eget, convallis purus. Cras tincidunt ipsum dui, sed laoreet mauris hendrerit vel. Nullam tincidunt odio dui, id placerat est sagittis sit amet. Nunc ut volutpat quam. Duis in mattis est. Morbi varius ex sed nulla congue, vitae dapibus tortor mattis.

Pellentesque tempor neque purus, sed luctus dolor feugiat vel. Nunc malesuada ex id ex imperdiet placerat. Donec eleifend, arcu in tempor lacinia, diam metus auctor quam, a porta sapien dui congue magna. Donec ut neque fermentum, interdum velit nec, facilisis ligula. Quisque fringilla tortor sit amet massa sagittis porttitor. Cras tristique posuere iaculis. Etiam varius tincidunt nulla non consectetur. Morbi lacus augue, pretium sit amet hendrerit sit amet, eleifend id turpis. Nullam posuere quis ex vel maximus.

Nam pharetra metus libero, sit amet malesuada quam pretium eu. Phasellus efficitur nec magna eget mollis. Morbi nec ex a libero hendrerit laoreet nec eu metus. Vestibulum non lacus feugiat, blandit neque at, sagittis eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas quis congue nunc, in tristique ligula. Suspendisse eu nisl eu erat interdum volutpat eu eu nisl. Phasellus sodales erat sit amet consectetur tempus. Duis mattis maximus risus, in vestibulum nunc dapibus a. Praesent consequat faucibus mauris nec placerat. Nam accumsan, ligula eget blandit semper, felis libero mattis eros, vitae blandit ipsum turpis malesuada ipsum.

Phasellus lobortis ipsum eget ex porttitor, id finibus ante hendrerit. Sed mattis ex nulla, a lacinia lectus varius in. Morbi egestas efficitur sem eu imperdiet. Nulla ullamcorper auctor velit, eget finibus ligula pellentesque ac. Cras a nisi ipsum. Nam vehicula ipsum et leo finibus mattis. Donec et eros diam. Phasellus tempor fermentum est in sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam pretium neque fermentum turpis cursus, vitae lobortis augue malesuada. Duis vel varius libero. Sed nec venenatis sapien, vitae porttitor ex. Nunc tempus diam vitae eros scelerisque maximus.

Donec finibus ex eu libero porta pulvinar. Cras at varius orci, a viverra libero. Proin maximus nulla id enim iaculis placerat. Praesent tempus nisl at nisl rhoncus rhoncus. Donec mollis nisi ac hendrerit auctor. Curabitur et dui et libero congue facilisis. Duis vel euismod dui, quis faucibus velit. Nunc hendrerit vehicula turpis id scelerisque.

Nulla accumsan lacus nulla, eu faucibus turpis sodales a. Sed lacinia ipsum ex. Nam mauris orci, faucibus eu sapien non, vestibulum sodales tortor. Praesent cursus feugiat posuere. Praesent metus augue, eleifend eu gravida a, pharetra sed justo. Maecenas id urna sit amet justo congue consequat. Nulla vitae sagittis lorem, eget auctor felis. Phasellus eleifend tortor eu semper mattis. Nullam dignissim tellus in laoreet imperdiet. In quis malesuada lorem, ac fermentum est. Ut sagittis tincidunt augue vitae sollicitudin. Vestibulum ornare magna velit, ac tempus ligula suscipit rutrum.

Donec enim dui, convallis eget massa ac, sagittis mattis justo. Curabitur euismod purus eu commodo semper. Donec tincidunt eros tortor, ac porttitor lorem ullamcorper id. Pellentesque a vehicula ipsum. Maecenas quis lectus efficitur, commodo dolor vel, sollicitudin nisl. Nullam sit amet orci at mi rutrum tincidunt feugiat at orci. Nullam sit amet eros ante. Mauris blandit molestie imperdiet. Phasellus tincidunt rutrum libero in finibus. Quisque commodo hendrerit dapibus. Nullam vel elementum lacus. Sed et lorem lobortis sem ullamcorper egestas at nec tellus. Aliquam at ante in dolor placerat ultricies.

Nunc quis viverra urna. Aliquam erat volutpat. Integer id metus tempus, pretium ligula nec, venenatis felis. Nam porta lectus sed purus fringilla dictum. Nunc aliquam varius tortor gravida feugiat. Morbi sapien enim, blandit sed accumsan a, mattis at nisl. Aliquam et arcu risus. Duis arcu libero, placerat fringilla nisl et, vulputate hendrerit leo. Maecenas eget magna enim. Nam pretium elit orci, eu dictum lectus vestibulum eget. Vivamus molestie risus quam, id mattis mi sodales nec. Etiam blandit maximus ipsum.

Aenean sed pellentesque sapien, eu tristique tellus. Nam massa mauris, luctus at consequat nec, finibus nec erat. Donec ultrices ut dui a lobortis. Vestibulum vestibulum eros felis, eget tristique nunc iaculis sit amet. Aenean id erat sit amet ligula tincidunt hendrerit. Donec vulputate dolor quis nibh maximus congue ac sit amet lorem. Pellentesque ornare elit vel commodo luctus. Phasellus non massa eu magna ornare suscipit ut id nisi. Pellentesque id justo ipsum.

Nullam venenatis ipsum ac ligula faucibus, ac aliquet purus finibus. Quisque vestibulum ultrices dolor, non pretium magna dignissim non. Etiam ut odio et nunc commodo venenatis. Donec sodales finibus ligula quis dignissim. Nunc sodales est at fermentum finibus. Praesent ex enim, placerat viverra tellus id, venenatis vehicula tortor. Cras dapibus, orci sed dapibus congue, risus metus tincidunt magna, non venenatis tellus lectus sit amet justo. Pellentesque imperdiet lorem ut tellus suscipit auctor. Nam sed ante dolor. Duis quis volutpat massa. Nam vitae finibus eros.

Nullam a sapien blandit, iaculis nibh eu, tincidunt augue. Maecenas iaculis leo et arcu luctus, id pharetra nisi interdum. Aliquam quis tellus eget purus commodo condimentum. Praesent nulla eros, fermentum eu venenatis vel, imperdiet vel massa. Proin a ultrices leo. Nam maximus dui quis mauris ornare, non auctor mauris luctus. Vivamus gravida, sem non commodo imperdiet, ante libero elementum libero, sed tristique mi velit sed sapien. Nulla bibendum gravida ligula. Sed ullamcorper suscipit nisi vitae malesuada. Suspendisse quis ante urna. Ut ac magna neque. In aliquam rutrum erat, et luctus dolor placerat vitae.

Pellentesque eu dui non nisi dictum maximus ut eu leo. Quisque in pretium massa, sit amet varius ipsum. Donec ornare lacinia diam eu elementum. Ut efficitur vitae libero at pulvinar. Donec vestibulum est ut blandit faucibus. Etiam rhoncus quam tortor, pharetra feugiat arcu lacinia vel. Suspendisse eget ex non nulla sodales suscipit vitae a lacus. Curabitur auctor, ante vel tempor laoreet, elit nisi fringilla orci, in varius sem enim at orci. Integer porttitor, massa in iaculis malesuada, sapien nibh tempus nunc, in consequat diam risus id sapien. Aenean dictum felis et suscipit interdum.

Vivamus sed mauris nec nunc interdum eleifend vel quis diam. Pellentesque aliquet euismod orci quis interdum. Pellentesque nulla tellus, vehicula eu felis laoreet, ullamcorper consequat nulla. Praesent in justo eu dui volutpat auctor eu sed mauris. Donec nulla ex, maximus quis dapibus vitae, viverra ut ligula. Donec vestibulum turpis ut tellus scelerisque, ac condimentum sem viverra. Fusce sodales mi vitae purus pharetra, id tempus magna convallis. Fusce ultricies tincidunt urna, sed varius leo iaculis quis.

In convallis felis quis leo ornare lacinia. Proin eu metus est. Vivamus arcu diam, porttitor eu mauris non, tristique lobortis metus. Aliquam eu leo ut nulla auctor blandit. Quisque aliquam eros at felis consequat semper in ac risus. Sed rutrum lectus ac odio posuere mollis. Praesent non posuere dui. Vestibulum at posuere tortor. Praesent sit amet lobortis velit, imperdiet interdum massa. Proin vel eros condimentum, mattis quam sit amet, ultrices velit. Morbi consequat ligula sit amet risus vehicula, in tincidunt metus cursus. Sed consequat tellus nec elit volutpat feugiat. Vivamus quis elit maximus, fringilla nisl sed, facilisis ligula. Praesent sit amet hendrerit nunc. Nulla placerat consequat rhoncus.

Sed malesuada nulla ut sapien posuere ultrices. Phasellus at placerat orci. Aliquam finibus ullamcorper lacus, eget rhoncus enim congue vitae. In elementum gravida nisi luctus mattis. Pellentesque blandit posuere magna eu semper. Cras pellentesque nulla neque, quis aliquet erat pellentesque ac. Phasellus iaculis, justo ac congue sagittis, elit justo laoreet dolor, et tincidunt erat felis eget tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse mollis feugiat diam, vitae fringilla lectus aliquam at. Fusce vitae tincidunt augue. Vivamus sit amet finibus est.

Maecenas fermentum nibh purus. Vivamus pharetra mi at finibus eleifend. Nunc ac venenatis ex, id rhoncus nisl. Nullam pretium nibh vitae lorem laoreet laoreet. Maecenas semper venenatis risus, vitae euismod elit cursus in. Etiam gravida ipsum in orci gravida, at eleifend ex accumsan. Aliquam ac vestibulum erat. Sed auctor non tortor eget viverra. Aliquam tincidunt nibh sapien, sit amet cursus purus eleifend in.

Donec vel euismod nibh. Curabitur quis libero eros. Vestibulum porta tellus velit, nec dictum lacus porttitor id. Mauris lacus ex, vulputate vitae tristique eu, viverra quis est. Quisque pellentesque lorem eros. Nullam auctor condimentum sem nec feugiat. Aliquam felis neque, porta eu dictum vitae, egestas et arcu. Sed finibus arcu mauris, non pharetra dui tincidunt vitae. Etiam condimentum tempus tortor eu ornare. Maecenas et bibendum nibh, id condimentum lectus. Donec lacus libero, interdum eu suscipit sit amet, scelerisque fringilla lorem. Donec commodo turpis eget nulla mollis, a aliquam lorem efficitur. In risus arcu, sodales sit amet imperdiet nec, ultrices ac justo. Maecenas et eros vel nunc maximus dignissim ullamcorper vel turpis.

Duis vel lorem tincidunt, egestas diam sed, fermentum augue. Aliquam dignissim vehicula cursus. Donec sollicitudin, nibh fringilla euismod porttitor, nibh lectus congue odio, sed sodales dolor sapien a ipsum. Donec ac tortor a augue auctor tempor ac id orci. Ut dignissim sapien non venenatis semper. Aenean ac euismod dolor. Nam sagittis dui justo, non molestie eros mollis ac. Nullam ac purus a risus scelerisque ornare et eget augue. Nam porttitor luctus eros. Fusce sodales eu lorem vitae suscipit. Suspendisse nec ex metus. Suspendisse lacinia tempor tortor, tristique commodo libero eleifend at.

Nunc scelerisque rutrum turpis, nec scelerisque nibh ullamcorper ut. Aenean nisi nisl, dapibus at ipsum congue, cursus lacinia enim. Praesent vestibulum sit amet nisi eget dignissim. Vivamus in mi metus. Vestibulum nec ante at risus lacinia pulvinar. In hac habitasse platea dictumst. Integer at sem eu mi dignissim faucibus vel eget magna. Etiam efficitur ut nibh et dignissim. Maecenas malesuada luctus faucibus. Cras sodales risus ut ultricies tempus. Nunc luctus at dolor in molestie. Donec id mi nisi. Aenean fringilla eu orci et fermentum.

Aenean luctus enim sit amet turpis ultricies egestas. Duis commodo dolor eget ullamcorper convallis. Donec at aliquam ex. Sed erat nisi, congue sed mauris ut, gravida vehicula lectus. Suspendisse tristique dui neque, at luctus sem ultrices maximus. Vestibulum consequat eros vel nisi scelerisque, ac eleifend risus mollis. Nam volutpat consectetur metus luctus commodo. Etiam at viverra turpis, commodo auctor ipsum. Aliquam erat volutpat. Cras at libero mi. Vestibulum finibus luctus pulvinar. Curabitur leo sem, consequat quis est non, pellentesque suscipit felis. Sed in elit non libero gravida laoreet.

Integer aliquam ipsum et nibh rhoncus, nec blandit nibh varius. Donec bibendum cursus augue a laoreet. Aenean quis sem at urna vehicula tincidunt. Aliquam eleifend, mauris non sagittis laoreet, nulla massa commodo magna, venenatis molestie neque eros in felis. Aenean laoreet, urna quis rhoncus viverra, urna enim lobortis turpis, eget lobortis felis odio sed mi. Cras mi lacus, dictum semper nisl pulvinar, eleifend dapibus urna. Vestibulum blandit quam ut dolor aliquet malesuada. Vestibulum non interdum ante. Proin facilisis metus posuere varius elementum. Pellentesque sed lacus et lacus convallis faucibus. Nullam orci nisl, eleifend et fermentum sed, finibus non odio. Phasellus eleifend est eros, vitae facilisis libero sodales vitae. Cras posuere eget ex eu dictum. Quisque non ultrices urna. Donec varius lectus at turpis blandit, nec volutpat ipsum ultrices. Donec venenatis lacinia metus sit amet ullamcorper.

Vivamus vitae elit eget felis viverra tristique pretium sit amet leo. Vestibulum at elit ac ante sollicitudin egestas. Nulla non viverra arcu. Mauris tellus odio, dignissim vulputate enim vitae, dictum varius ligula. Quisque velit augue, sodales eget volutpat sit amet, posuere ut lacus. Sed vel euismod ipsum. Nam porta id nisl in ultricies. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis non odio sit amet urna fermentum varius. Nulla eleifend odio in tellus elementum luctus. Cras at auctor lacus. Donec nec sem quis magna molestie tincidunt. Nunc ultricies diam in sapien feugiat, at euismod leo porttitor. Donec id est et quam laoreet sollicitudin sit amet nec velit.

Integer eleifend magna at mi varius tristique ac vitae enim. Sed lacus quam, congue a tempus in, auctor nec diam. In fringilla faucibus fermentum. Integer vitae consequat diam. Nulla at tempus enim. Pellentesque commodo nulla elit. Aliquam molestie mi eu sapien volutpat commodo. Nunc elementum ornare libero, ut rutrum ex volutpat quis. Fusce tempor pellentesque magna sodales aliquet. Donec mollis nisl eu leo tempus fermentum. Mauris suscipit elit turpis, dapibus pretium enim laoreet in. Vivamus at consectetur arcu. Cras cursus feugiat justo eget interdum. Donec mollis ut libero non bibendum.

Aenean eu leo sapien. Mauris quam augue, tempus id commodo quis, venenatis eu lectus. Sed vitae nibh ultricies erat venenatis dapibus nec ac neque. Quisque sagittis libero nibh, quis molestie ante vehicula cursus. Curabitur ipsum diam, gravida ac interdum nec, pulvinar ac quam. Etiam pharetra, mauris ac pharetra porttitor, urna orci cursus leo, quis rutrum lacus erat id nulla. Sed velit massa, luctus rutrum mi dapibus, euismod rhoncus dolor. Quisque a mi pharetra, eleifend augue vel, volutpat metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus id nibh vel sem ultricies consectetur non in eros. Donec tincidunt, neque id placerat dignissim, lectus sem consequat sem, in varius turpis arcu non risus. Integer vel quam vel enim fermentum blandit. Cras ut magna volutpat metus euismod pharetra.

Ut non ex eu nisi pellentesque congue. Pellentesque vitae elit dictum, blandit lorem eu, ornare ex. Morbi rhoncus scelerisque dolor, nec venenatis elit consectetur vel. Aliquam vulputate velit eu dignissim vestibulum. Vivamus condimentum sapien nec fringilla venenatis. Aliquam id vehicula mi. Nullam in dui interdum, ullamcorper nisi iaculis, blandit ex. Cras sed fringilla nisi. Nam ipsum lorem, volutpat at rhoncus vestibulum, sollicitudin id elit. Proin commodo justo non bibendum ornare. Phasellus iaculis elit eget nibh tincidunt mollis. Nunc ornare quam et erat efficitur malesuada. Sed fringilla diam in sem accumsan, id fermentum nisi posuere.

Curabitur ornare sem at est tristique hendrerit. Cras luctus ex eu viverra sodales. Fusce at metus enim. Nunc nunc nisl, aliquam non ornare sed, porta sed dolor. Maecenas quis erat velit. Duis ac eros a mauris tristique laoreet. Vestibulum gravida magna nisl, ut tristique dui viverra eget. Sed dignissim, lectus ac maximus pretium, enim metus porttitor arcu, nec hendrerit elit libero et ipsum. Mauris euismod risus eget nisl finibus pellentesque. In orci sem, accumsan sit amet ultrices sed, ornare vel lacus. Ut sed augue libero. Nulla et consectetur risus, et sagittis nibh. Sed leo justo, tristique faucibus est eget, viverra mattis urna. Aliquam ultricies purus vitae lacus tempus, sit amet ultrices dui hendrerit. Pellentesque efficitur convallis quam, quis vestibulum velit varius vel.

Nunc pretium eu massa nec ullamcorper. Phasellus eu vehicula velit, ullamcorper hendrerit odio. Donec congue in dolor in finibus. Maecenas odio nunc, eleifend eget fermentum eget, luctus ac dui. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed turpis mauris, viverra sit amet dui non, bibendum suscipit orci. Fusce pretium suscipit erat non rhoncus. Praesent lobortis tortor eu mi euismod posuere. Sed fringilla tincidunt turpis. Sed luctus urna quis dignissim posuere. Aliquam sapien nulla, eleifend et nibh sit amet, rhoncus fringilla augue. Sed iaculis risus a sagittis dignissim.

Ut et eros accumsan neque commodo molestie. Fusce bibendum nibh in diam tincidunt ultricies. Morbi blandit scelerisque nunc, sit amet laoreet diam efficitur posuere. In ac semper mi. Aenean laoreet felis vitae nulla ultrices, iaculis condimentum tortor bibendum. Donec bibendum vitae libero a consectetur. Curabitur varius faucibus condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Vestibulum consequat tincidunt augue id hendrerit. Aenean eu vestibulum metus, in aliquet odio. Duis accumsan pulvinar justo sed tempor. Aenean faucibus ligula rhoncus lacus tincidunt, ornare varius neque posuere. Phasellus convallis bibendum sodales. Fusce dignissim egestas purus nec dictum. Curabitur quis libero orci. Aliquam non sollicitudin odio. Integer quis eros efficitur, condimentum lorem hendrerit, aliquam diam.

Vivamus iaculis ex tortor, in sagittis justo condimentum a. Pellentesque pretium tortor mi, non pharetra mauris efficitur eu. Morbi porta sapien sapien, a finibus velit eleifend sit amet. Nulla vulputate iaculis sem nec imperdiet. Nunc malesuada ex ut ornare pellentesque. Nam ullamcorper nisi purus, eu pharetra velit ultricies et. Aenean tincidunt ultricies eros. Nunc id varius ex. Morbi fringilla accumsan tincidunt. Morbi sit amet nisl mi. Nunc porttitor eu lorem at bibendum. Sed mattis, diam at egestas hendrerit, purus libero molestie ex, a tincidunt lorem justo a lacus. Aliquam augue ante, cursus sed urna fringilla, blandit varius lectus. Ut nec augue euismod, interdum nulla sit amet, ultrices augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sit amet feugiat nulla, et accumsan velit.

Vivamus scelerisque eget neque id aliquet. Suspendisse potenti. Curabitur sodales auctor nisi, malesuada sodales magna aliquam at. Cras ac dapibus tellus, sed pulvinar lorem. Nulla sollicitudin velit nec vulputate dignissim. Duis sed tempus nulla, nec rhoncus nisi. Vivamus placerat maximus tellus eget tristique.

Quisque vitae vestibulum sem. Suspendisse posuere ullamcorper augue, nec sollicitudin urna varius eget. Fusce tempor est erat, eu faucibus lorem tincidunt et. Integer ac dui condimentum, placerat lacus sed, tincidunt justo. Maecenas eleifend ipsum et orci blandit, vel vulputate sapien condimentum. Etiam id nunc felis. Quisque ultrices ex egestas malesuada mollis. Suspendisse fringilla diam vel metus dictum, mattis eleifend lacus pharetra. Praesent ac nibh in lacus blandit consectetur. Aliquam tincidunt lacus ac ultricies viverra. Integer euismod urna ut nulla bibendum scelerisque. Maecenas volutpat libero eu urna luctus, id malesuada nisl elementum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Donec eget nisi volutpat, rhoncus massa eu, tincidunt diam. Suspendisse at suscipit nisl, id pharetra quam. Nulla vestibulum malesuada nunc, ut viverra massa dictum et. Fusce eget quam at tellus ultrices euismod. Praesent pellentesque, libero non imperdiet sagittis, nisi ex venenatis tortor, nec rhoncus ante risus eget est. Quisque non rhoncus eros. Nunc vulputate eu sem quis pharetra. Sed accumsan est eget nunc laoreet, nec volutpat justo dictum. Aliquam erat volutpat. Vivamus blandit est ut tincidunt rhoncus. Praesent efficitur posuere diam, quis blandit massa viverra et.

In bibendum sit amet mi vel volutpat. Morbi quis nunc erat. Ut eleifend sagittis tellus. Sed tempor, est et pretium pellentesque, diam nulla vulputate erat, non blandit erat metus ut odio. Nunc eleifend pulvinar malesuada. Proin et varius erat, fringilla vehicula enim. Mauris lectus ligula, suscipit eget hendrerit non, porta at diam. Morbi facilisis erat tincidunt porttitor varius. Ut tempus ligula eu imperdiet sollicitudin. Sed tincidunt neque quis pharetra tristique. Donec a rutrum nunc.

Vestibulum orci nulla, interdum in rhoncus ac, finibus vel sem. Ut elit eros, suscipit nec porta id, sagittis mattis lacus. Integer sodales dolor nec ipsum imperdiet lobortis. Donec tristique orci et diam bibendum, ut maximus orci efficitur. Mauris egestas lacinia viverra. Cras gravida, dui tincidunt varius sodales, lorem ante vehicula enim, in lobortis mi quam non lacus. Aliquam ac lorem sed dolor dignissim rutrum a eget ligula.

Sed dictum accumsan libero a porta. Nulla facilisi. Phasellus ornare bibendum molestie. Donec at porttitor quam. Aenean fringilla dictum erat id aliquam. Sed lobortis tincidunt luctus. Praesent congue risus ac nunc ultrices aliquam. In hac habitasse platea dictumst. Vivamus faucibus nibh vel nibh bibendum, ut congue orci commodo. Nunc ullamcorper, elit eget tincidunt tempus, erat tortor placerat felis, semper commodo tellus nisl et leo. Proin pulvinar ac velit et sagittis.

Aliquam consequat eu ligula quis mollis. Sed ut mauris sapien. Etiam sit amet tellus leo. Phasellus ac turpis laoreet, fermentum nisi vitae, dignissim risus. Pellentesque a mi ut dolor hendrerit ullamcorper id sed ex. Nullam id est condimentum, facilisis magna at, scelerisque arcu. Vestibulum tortor neque, eleifend sit amet rhoncus vel, mattis id ex. Suspendisse arcu justo, malesuada eu lacus ut, bibendum placerat velit. Proin ornare in nibh id hendrerit. Cras accumsan aliquam risus, id sollicitudin ex cursus eu. Duis porta massa sit amet suscipit porta.

Mauris feugiat, leo in dapibus suscipit, enim lorem aliquet ipsum, id lacinia turpis velit vitae enim. Nulla turpis augue, iaculis vel libero at, bibendum placerat neque. Suspendisse tempor, tortor ac fermentum dictum, dolor leo pulvinar mi, in mollis nisi leo vulputate diam. Sed iaculis luctus lacus, ut iaculis velit pulvinar quis. Mauris dignissim sem quis vestibulum iaculis. In hac habitasse platea dictumst. Integer suscipit posuere tortor, in sagittis lectus dictum a. Vivamus malesuada lobortis neque non dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur molestie, eros sollicitudin dignissim pulvinar, eros odio rhoncus turpis, nec viverra nisl elit nec ligula. Cras et sapien efficitur leo semper dignissim sed in urna. Sed nunc dolor, euismod ac tincidunt cursus, pellentesque id erat. Vestibulum et sollicitudin dolor, ut varius magna.

Fusce lobortis sapien sem, eu placerat lacus tincidunt non. Quisque varius lorem et sagittis mollis. Nulla lacinia purus a augue ornare, ut fringilla nulla mattis. Nam sit amet dui vel ipsum eleifend feugiat sed a nibh. Ut in turpis et ipsum facilisis varius a non erat. Duis ut urna scelerisque, consequat eros ac, ornare tortor. Duis laoreet nibh eget tincidunt blandit. Pellentesque pharetra ornare augue ut imperdiet. Vivamus tortor nunc, facilisis eu purus in, aliquam vestibulum ex. Curabitur aliquet eros non diam luctus, in sollicitudin nulla faucibus. Mauris viverra leo sit amet arcu pulvinar, sit amet accumsan ante pellentesque. Nullam a arcu odio. Sed imperdiet sapien mauris, ut vestibulum quam pulvinar vitae. Nam quis luctus risus. Fusce sit amet dignissim sapien. Cras quis aliquam tellus, efficitur pharetra lacus.

Aenean dolor lectus, tristique quis molestie et, posuere id augue. Aliquam pharetra non augue eget blandit. Pellentesque a scelerisque metus. Phasellus sollicitudin tellus eget purus interdum hendrerit. Sed lacinia diam ut nisi porta placerat. Integer dapibus, justo id lobortis lacinia, nisi quam pellentesque ligula, sit amet dapibus dolor tortor non ipsum. Curabitur sodales leo ex, sit amet tristique lorem vestibulum ac. Fusce faucibus justo sed neque varius dignissim. Curabitur imperdiet tellus eu lorem volutpat consequat.

Aenean tempus justo eget fermentum mattis. Duis viverra arcu nec purus luctus, eu sagittis ipsum ultricies. Sed eleifend ex nec nisi tempus ultricies. Quisque nec mauris eu magna porta tincidunt. Aliquam tristique felis quis nulla vestibulum porttitor. Aenean convallis magna eu turpis molestie ornare. Duis id lobortis velit, at molestie tellus. Ut efficitur ultrices quam sed eleifend. Vivamus lectus risus, pharetra nec lacinia ac, egestas sed erat. Mauris sollicitudin sem a cursus bibendum.

Praesent eu odio sit amet arcu varius hendrerit. Etiam metus ante, pharetra et aliquet nec, interdum id orci. Nam odio magna, suscipit nec dolor nec, scelerisque fringilla orci. Quisque ultrices sed mi in congue. Nulla eu bibendum quam. Ut placerat neque vitae elit ullamcorper dapibus. Phasellus non maximus erat. In at laoreet felis. Morbi et tellus posuere, aliquam tellus sed, luctus quam. Nam ullamcorper rhoncus turpis malesuada varius. Donec vitae nisl fringilla elit elementum facilisis sed vitae nunc.

Integer volutpat risus in suscipit bibendum. Duis ultricies mattis pellentesque. Sed non molestie dolor. Ut et mi sed sem vehicula aliquet sit amet quis sapien. Ut arcu orci, facilisis ut erat sed, rutrum hendrerit mauris. Phasellus non urna id augue consectetur blandit sit amet facilisis mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed commodo, arcu quis tristique blandit, orci est tempus magna, id luctus nisl augue non lectus. Suspendisse lectus mi, dictum ac nibh at, tincidunt vestibulum lectus. Nulla tempor in sapien id vestibulum. Sed ut gravida orci.

Aenean et odio tellus. Sed vulputate nulla vel quam suscipit porta ut ut velit. Nunc tempus urna vel lorem posuere lacinia. Fusce a gravida diam. Maecenas fringilla, eros vitae pharetra auctor, erat tortor sodales nisi, sit amet posuere odio magna eget nisl. Nam in feugiat metus. Duis nec sodales quam, non ullamcorper sapien.

Morbi a dui eget neque auctor ultrices vel a tellus. Praesent et molestie arcu. Sed auctor cursus arcu, a luctus elit iaculis sit amet. Vivamus ac sapien ac neque elementum viverra. In in nunc ac erat cursus ornare quis eget neque. Sed vulputate nibh eu mi feugiat dignissim. Etiam facilisis urna iaculis nibh cursus consectetur. Nullam sed ornare mauris, vitae rhoncus justo. Sed vel felis et nisi facilisis imperdiet. Nullam ut tristique risus. Nam interdum nunc eget consectetur semper. Aliquam eget ex a felis aliquet laoreet. Donec consectetur blandit elit sed eleifend. Sed efficitur, dolor sed pharetra porttitor, tellus urna condimentum dolor, sit amet accumsan libero nunc sed enim. Phasellus sit amet enim id nisl imperdiet commodo at sit amet ex.

Praesent vitae neque consequat, luctus sapien a, sollicitudin lectus. Cras pellentesque bibendum dui, at consequat justo viverra vitae. Suspendisse potenti. Nulla facilisi. Sed et turpis quis tortor dictum blandit. Quisque non erat hendrerit nisl dictum interdum. Duis tempor metus vel malesuada laoreet.

Curabitur egestas sodales nisi a scelerisque. Phasellus ut augue eros. Nullam accumsan vel dui et pretium. Integer pharetra mauris vel congue maximus. Ut sed diam tortor. Vestibulum vel arcu sit amet mi vulputate luctus vitae a massa. Integer sit amet mauris tempus, hendrerit enim a, ornare urna. Vestibulum ullamcorper mi non odio vestibulum, at tincidunt lacus tempor. Fusce a hendrerit diam, nec porttitor urna. Nam feugiat purus nec est eleifend consequat. Vivamus tincidunt egestas tortor, eu accumsan quam dapibus quis. Maecenas accumsan elit id mauris auctor, ut facilisis quam egestas. Sed a odio vitae sem interdum condimentum a at augue. Aliquam blandit nunc nec nisl facilisis, tincidunt auctor eros ultrices.

Sed sagittis nisl sagittis dui rhoncus efficitur. Maecenas bibendum odio vestibulum mauris accumsan lacinia eu at tortor. Donec pharetra id neque pretium ullamcorper. Vestibulum blandit est at sapien dictum, sit amet mattis ex malesuada. Vivamus vitae elementum lectus. In condimentum finibus pellentesque. In tristique luctus augue. Suspendisse in dui dolor. Pellentesque interdum a elit a iaculis. Cras condimentum nisi nibh, quis ornare ex tincidunt quis. Vivamus eget egestas urna. Donec dictum lorem dapibus, placerat purus et, suscipit erat. Duis mattis arcu a finibus feugiat. Nunc mattis feugiat tellus eget commodo. Phasellus nec quam quis libero consectetur ornare.

Maecenas fermentum neque et eros posuere lobortis. Sed convallis tortor in fringilla venenatis. Nulla efficitur massa dignissim odio porta, et varius neque malesuada. Proin non semper nibh, ac sollicitudin nisi. Aliquam porta, justo sed finibus posuere, turpis nibh condimentum nunc, sed commodo augue erat a nisi. Maecenas augue lectus, pharetra ac varius nec, condimentum sit amet urna. Duis fermentum orci nec lacinia fermentum. Morbi at finibus ex, nec sagittis odio.

Aenean urna justo, congue a sem id, faucibus faucibus tortor. Nullam enim dui, semper eu orci vitae, pretium sollicitudin nibh. Sed quis diam posuere, lacinia ipsum quis, vulputate ante. Mauris pulvinar tortor vitae arcu scelerisque, sed tincidunt ante posuere. Nulla facilisi. Quisque eget felis accumsan, hendrerit elit id, iaculis libero. In porta, augue ac euismod eleifend, ligula lectus tempus ipsum, nec egestas nulla nibh sed quam. Proin efficitur leo sapien. Curabitur ligula lorem, maximus commodo ex ut, ultrices imperdiet purus. Pellentesque ac erat augue. In hac habitasse platea dictumst. Vestibulum varius nibh eu massa posuere, ac euismod justo sodales. Curabitur egestas nulla vel sagittis sagittis. Aliquam eleifend arcu vel ex euismod, non gravida augue vulputate. Sed condimentum imperdiet massa non malesuada.

Aenean vel ligula id urna pharetra suscipit. Nunc eget feugiat augue. Aenean a est et dolor egestas cursus maximus a lectus. Duis varius nunc nec nisi mollis, eu varius eros congue. Mauris vehicula lacus id dui mattis, quis sodales dui aliquet. Mauris tempus dolor urna, non dapibus est pretium ac. Nullam lacinia, tortor id sodales lacinia, tortor quam pulvinar leo, sed dictum magna tellus sed eros. Donec et nisi id lorem pretium bibendum ut in sapien. Sed venenatis euismod nisi sed condimentum. Praesent elementum, lorem ac bibendum mollis, ex nisl tristique elit, eu consectetur risus ipsum sit amet augue. Nunc commodo dui vel finibus semper. Suspendisse potenti. Quisque eu ligula gravida, fermentum est lacinia, sagittis lacus. Quisque sit amet sem vitae libero iaculis varius.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam in est ornare, pellentesque massa eget, egestas sem. Aenean a metus est. Donec a suscipit lorem, condimentum imperdiet justo. Nulla maximus velit ac risus gravida porttitor. Sed a euismod leo. Nam a nulla a nisl auctor eleifend eu eu augue. Etiam tempor erat orci. Aliquam eu convallis risus. Nunc consequat, leo sed vehicula posuere, lorem lacus egestas magna, id fermentum felis nunc non massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam dictum imperdiet orci.

Praesent blandit lorem blandit, accumsan elit eget, ornare ante. Nullam nunc justo, fringilla ac nunc et, porta gravida massa. Sed sollicitudin, nunc ac consectetur venenatis, metus justo semper magna, eu tincidunt augue tortor eu est. Nulla ac odio sed metus feugiat feugiat sed vitae nunc. Sed ultrices dignissim justo, et consectetur velit ultricies tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis efficitur ligula vel augue fermentum interdum. Morbi rhoncus mauris a massa blandit rutrum. Nulla bibendum malesuada malesuada. Nunc fringilla ultricies turpis sed consequat. Curabitur molestie mi eu diam consectetur ullamcorper. Nullam id dui ut erat tincidunt luctus ac nec dolor. Nam porta odio sapien, non semper mauris pretium vitae. Donec iaculis, turpis vel bibendum scelerisque, purus tellus convallis lectus, et maximus libero neque nec diam.

Vestibulum et nunc vulputate, eleifend velit ac, pharetra nunc. Sed et sem lorem. Vestibulum scelerisque commodo sapien, id volutpat velit efficitur nec. Phasellus felis enim, aliquet a consequat vel, dapibus quis sem. Maecenas lectus est, iaculis ut erat non, condimentum cursus est. Fusce semper orci in odio interdum, sed iaculis augue porta. Integer eu porttitor orci, eget mollis ante. Duis nisi urna, pharetra et massa ac, luctus tincidunt metus. Nam eu dignissim ex. Pellentesque ornare diam nec turpis venenatis, ut ullamcorper est malesuada. Etiam auctor, leo id cursus ultricies, mi turpis vulputate tellus, vitae congue justo magna suscipit nisl. Cras id faucibus ante.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur scelerisque felis et lorem cursus sagittis. Donec felis mauris, fringilla non metus nec, fermentum facilisis libero. Donec varius condimentum tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse eu eros ac dolor congue scelerisque. Mauris eget odio vitae enim consectetur imperdiet. Pellentesque lobortis tristique odio et lacinia. Nullam tristique tempor nisl et rutrum. Duis ut faucibus ipsum.

Proin turpis purus, egestas sed ullamcorper eu, suscipit sit amet orci. Maecenas sollicitudin feugiat neque sed tincidunt. Praesent laoreet augue varius metus semper, id mollis massa ultricies. Praesent at vestibulum est. Nam gravida mi urna, in sodales mi dignissim id. Suspendisse volutpat sed massa quis iaculis. Etiam viverra iaculis enim, eget elementum augue auctor ac. Integer volutpat, nisl a sagittis congue, urna neque blandit nibh, at mattis augue metus in magna. Quisque sodales, lorem at finibus molestie, eros purus volutpat erat, quis pharetra dui augue a quam. Proin in molestie nunc. In ut gravida diam. Mauris pulvinar scelerisque dolor. Praesent ullamcorper, nisi in pharetra placerat, eros dolor sagittis turpis, quis vehicula sem purus in sapien. Mauris tempus erat a metus ultrices, sit amet ullamcorper nibh finibus.

Pellentesque neque sapien, feugiat at aliquet id, laoreet quis lorem. Nam tincidunt convallis nibh et accumsan. Sed pulvinar leo nibh, a facilisis dui ornare sed. Integer sodales eleifend magna at iaculis. Quisque dapibus vel ex ac congue. Sed est ligula, finibus vitae consequat et, auctor quis enim. Maecenas nec ultricies ipsum, pretium lacinia ex.

In viverra ultricies enim, non elementum nulla congue tempor. Suspendisse at diam at justo pulvinar porttitor. Cras nisi justo, aliquam ac sapien quis, porttitor dapibus libero. Mauris id sapien congue, luctus massa vitae, hendrerit ex. Nullam at magna sit amet risus scelerisque rhoncus in vitae ligula. Nullam imperdiet risus enim, sed fermentum erat dapibus ut. Maecenas condimentum sapien a vehicula venenatis. In sit amet tristique augue, vel feugiat justo. Sed ut ligula vel ex aliquet egestas eu a lorem. Nullam dapibus ex quam, nec feugiat velit luctus in. Morbi molestie pretium nisi, malesuada molestie ipsum varius malesuada.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam at commodo tellus, sit amet dignissim diam. Phasellus facilisis sem at laoreet placerat. Integer pharetra condimentum lorem, et tempor arcu ornare vel. Vivamus sit amet dui sem. Vivamus cursus lacus mollis magna facilisis, non euismod est malesuada. Etiam sed sapien dapibus, imperdiet nunc sit amet, sodales quam. Fusce bibendum vehicula lectus, et commodo purus volutpat vitae.

Donec eget sem sit amet magna placerat rhoncus. Fusce sapien augue, viverra ut est at, sollicitudin tincidunt massa. Quisque tristique, neque non malesuada auctor, nulla leo tristique libero, sit amet fermentum ex tellus dictum quam. Nunc quis risus egestas, condimentum neque id, consequat magna. Etiam id lacus mattis, ultrices massa ac, sollicitudin neque. Phasellus quis massa consectetur, ullamcorper tellus ac, viverra nibh. Aenean risus felis, eleifend condimentum diam id, sodales convallis mauris. Cras in odio dolor. Suspendisse potenti. Duis commodo lorem eget aliquet commodo. Nam bibendum et risus vitae consectetur. Aliquam erat volutpat. Nunc sollicitudin pharetra tortor nec suscipit. Cras bibendum sem nunc, egestas euismod felis ultrices ac. Pellentesque ut eleifend lorem. Morbi blandit libero in sapien porttitor cursus.

Nullam nec mi vel nibh pharetra suscipit. Nulla lectus est, molestie sit amet porta a, pharetra sed libero. Proin varius porta velit, sit amet eleifend urna euismod a. Curabitur pharetra eget velit a ultricies. Nunc quis elit massa. Aliquam iaculis tortor quis risus egestas rutrum. Nullam nec lorem sit amet sapien pretium interdum id sit amet libero.

Sed ornare, nunc nec semper molestie, augue tellus lobortis lacus, a finibus elit nulla non nunc. Duis ut sollicitudin libero, sit amet pulvinar nisi. Suspendisse sed nunc sit amet arcu dignissim porta id et nunc. Sed eget eros consectetur, finibus metus at, viverra justo. Nulla hendrerit congue porta. Fusce ac elit in libero hendrerit luctus sit amet ut tortor. Sed imperdiet in tortor ut vehicula. Ut elementum eu eros sit amet dictum. Proin facilisis id elit vitae placerat. Nam vitae pretium est, faucibus efficitur felis. Aenean ut dolor enim. Aenean id magna consequat, dictum neque nec, varius sapien. Praesent vehicula ornare augue, non rhoncus justo eleifend quis.

Duis nec erat cursus, placerat mauris egestas, bibendum odio. Aenean ac lorem tempus, molestie dolor non, fringilla enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sollicitudin massa ac porta congue. In urna nunc, congue eget auctor id, pulvinar sit amet odio. Vivamus purus erat, dictum quis fringilla in, semper sed tortor. Ut fringilla eros ut rhoncus gravida. Maecenas sollicitudin gravida consequat. Etiam efficitur tincidunt dictum. Aliquam placerat nunc elit. Donec nec turpis justo. Fusce massa risus, tincidunt et mollis sit amet, lobortis non tortor.

Nullam mollis, risus sit amet scelerisque dictum, eros est sollicitudin nulla, quis tincidunt nisl sem quis tellus. Sed dictum posuere sapien, in bibendum nisi pharetra non. Aliquam dictum neque in ante sodales volutpat. Etiam sagittis sodales diam eget rutrum. Aenean in quam convallis, sodales felis id, sagittis risus. Nulla nec ipsum nec diam rhoncus sodales quis ac elit. Vestibulum bibendum rutrum dolor, vitae tristique erat euismod eget. Quisque sollicitudin commodo urna. Duis non nisl ornare, ultricies ante non, interdum metus. Fusce gravida felis nisi, id pulvinar metus convallis a. Cras pretium est sed mollis ullamcorper. Nunc eleifend magna ut purus consequat convallis. Duis vitae imperdiet lectus. Suspendisse potenti. In in tortor nec metus tincidunt.
"""
resultado8 = conn1.echo(texto_largo)
if (texto_largo == resultado8):
    print('conn1.echo(texto_largo) -> se recibio el mismo string que texto_largo')
else:
    print('Error en conn1.echo -> no se recibio el mismo string que texto_largo')

#Implementar un método que tarde mas de 10 segundos en responder
print("<--- Ejecutando time.sleep! -->")
resultado9 = conn1.timeout(15)
print(f'conn1.timeout(15) = {resultado9}')
assert resultado9 == True, f'Error en conn1.timeout: {resultado9} != True'

print('--------------------------------')
print('ERRORES SERVER1:')
print('--------------------------------')
#Error No existe el método invocado

try:
    resultado_error1 = conn1.noExisteMetodo()
except Exception as e:
    print(e)

#Error en parámetros del método invocado
try:
    resultado_error2 = conn1.construirFloat()
except Exception as e:
    print(e)

try:
    resultado_error3 = conn1.construirFloat(1)
except Exception as e:
    print(e)

try:
    resultado_error4 = conn1.construirFloat(3, 3, 3)
except Exception as e:
    print(e)

try:
    resultado_error5 = conn1.construirFloat('abc', 'd')
except Exception as e:
    print(e)

#Error interno en la ejecución del método (Division por 0)
try:
    resultado_error6 = conn1.divisionReales(10, 0)
except Exception as e:
    print(e)

print('--------------------------------')

print()

print('Funciones Servidor2: ')

resultado6 = conn2.listsToMap(['a','b','c'],[1, 2]) # LAS CLAVES EN UN DICCIONARIO DE XLRPC DEBEN SER STRINGS
print(f'conn2.listsToMap([\'a\',\'b\',\'c\'],[1, 2]) = {resultado6}')
assert resultado6 == {'a': 1, 'b': 2}, f'Error en conn2.listsToMap: {resultado6} != {{"a": 1, "b": 2}}'

resultado7 = conn2.concatStrings('hello', 'world', '!', '!', '!')
print(f'conn2.concatStrings(\'hello\', \'world\', \'!\', \'!\', \'!\') = {resultado7}')
assert resultado7 == 'helloworld!!!', f'Error en conn2.concatStrings: {resultado7} != helloworld!!!'

resultado8 = conn2.existe([1, 2, 3, '4', 5, 'i'], 'j')
print(f'conn2.existe([1, 2, 3, \'4\', 5, \'i\'], \'j\') = {resultado8}')
assert resultado8 == False, f'Error en conn2.existe: {resultado8} != False'

resultado9 = conn2.agregarElemento({'a': 1, 'b': 2}, 'c', 3)
print(f'conn2.agregarElemento({{"a": 1, "b": 2}}, \'c\', 3) = {resultado9}')
assert resultado9 == {'a': 1, 'b': 2, 'c': 3}, f'Error en conn2.agregarElemento: {resultado9} != {{"a": 1, "b": 2, "c": 3}}'

resultado10 = conn2.construirListaEnteros(1, 10)
print(f'conn2.construirListaEnteros(1, 10) = {resultado10}')
assert resultado10 == [1,2,3,4,5,6,7,8,9,10], f'Error en conn2.construirListaEnteros: {resultado10} != [1,2,3,4,5,6,7,8,9,10]'

resultado11 = conn2.encode('Hello world!')
print(f'conn2.encode(\'Hello world!\') = {resultado11}')
assert resultado11 == b'SGVsbG8gd29ybGQh', f'Error en conn2.encode: {resultado11} != b\'SGVsbG8gd29ybGQh\''

resultado12 = conn2.decode(b'SG9sYSBtdW5kbyE=')
print(f'conn2.decode(b\'SG9sYSBtdW5kbyE=\') = {resultado12}')
assert resultado12 == 'Hola mundo!', f'Error en conn2.decode: {resultado12} != \'Hola mundo!\''